### ISSUE TITLE
When the exception is logged it will be repeated too much times

### ISSUE THREAD

**Issue by SamueleLorefice** [SamueleLorefice/TelegramSharp#2]
When program encounters an exception this will not wait a bit before trying again, this causes the exception to be logged a lot of times ending up of a really large error  log file (over 1MB for 20 seconds). This is know to happen for web exception only.
Solution: wait a bit before retrying connection or not log the exception if is the same.

**Comment by Steffo99** [comment]
E se ho capito bene, oltre a darti l'errore millemila volte, vieni ratelimitato da Telegram (puoi mandare max 5 richieste in 1 secondo e dopo ti dà 429) per un po' di tempo, causando ancora più errori...
giusto?

**Comment by SamueleLorefice** [comment]
@Steffo99 esatto, ma quello è diverso, perchè il logging è in parallelo, a prescindere il mio bot gira su un loop infinito

**Comment by Steffo99** [comment]
Non potresti mettere `System.Threading.Thread.Sleep(`un po'`);` da qualche parte, tipo dopo l'errore...? Tipo per 200ms

**Comment by SamueleLorefice** [comment]
@Steffo99 continuerebbe a spamamrlo, invece potremmo usae un controllo epr vedere se l'errore è lo stesso e quindi evitare di loggarlo

**Comment by Steffo99** [comment]
Sì, ma così non risolvi il problema del rate limiting :stuck_out_tongue_closed_eyes:

**Comment by SamueleLorefice** [comment]
@Steffo99 Che accade solo se sto per inviare un messaggio, quindi li absta un time rper contorllare quanit messaggi al secondo posso inviare

**Comment by Steffo99** [comment]
No, qualsiasi metodo, anche getUpdates (con o senza errore), può dare un rate limit...
Però se vuoi anche risparmiare sullo spazio del log converrebbe mettere sia il timer sia il controllo...
Hai qualche idea di come farlo? Perchè tornare a leggere il file e confrontare le stringhe mi sembra un po' lento...

**Comment by SamueleLorefice** [comment]
@Steffo99 getupdates lo spammavo 1 volta ogni ms e tranquillamente non mi ha mai ratelimitato

**Comment by Steffo99** [comment]
Allora forse adesso l'hanno tolto.
Mi ricordo quando ho fatto il mio primo bot per imparare il python dovevo mettergli un delay di 100ms se no mi dava errore...
(O forse, ora che ci penso, forse era telecom che mi ratelimitava :disappointed: )

**Comment by SamueleLorefice** [comment]
@Steffo99 ok, investigheremo dopo, per evitare di controllare il log basta che ogni errore avviamo uno stopwatch, al prossimo contorlliamo quanto tempo è passato, se minore di tot e l'errore è identico skippiamo.
